### ISSUE TITLE
Error when uninstall

### ISSUE THREAD

**Issue by jza34** [dizoocs/slider#21]
Hi, I am not able to uninstall this plugin from the backend. I get this error :
`"SQLSTATE[HY000]: General error: 1 no such column: image_align (SQL: CREATE TEMPORARY TABLE __temp__dizoo_slider_slides AS SELECT id, title, sort_order, subtitle, description, button_1_active, button_1_text, button_1_color, button_2_active, button_2_text, button_1_url, button_2_url, active, text_align, image_align, subtitle_size FROM dizoo_slider_slides)" on line 664 of /var/www/dev/pousse-graine/vendor/laravel/framework/src/Illuminate/Database/Connection.php`

**Comment by Dahfrenk** [comment]
That is odd, I just tested uninstalling and it works fine, the image_align column came with update 1.1.0. Did you update it to the latest version before uninstalling it?

**Comment by jza34** [comment]
I am a new user of OctoberCMS. I installed this plugin last week, version 1.1.2. No update since there. I tried again few minutes ago and it still fails with same error.
Edit : I forgot to tell you I use SQlite db in OctoberCMS
Edit 2 : I did some query to the database with CLI sqlite3 and you are right it works...I mean no error with same query, image_align is present indeed. Error only present from the OctoberCMS backend

**Comment by Dahfrenk** [comment]
I am unable to duplicate the problem, I use MariaDB myself but I have added a check in the update files to check for the field and only run the query once the field is found. Could you update the plugin and see if the problem persists? PR https://github.com/dizoocs/slider/pull/23

**Comment by jza34** [comment]
Sure! Could you please tell how to update the plugin from your project files because I never installed a plugin outside the backend/marketplace...

**Comment by Dahfrenk** [comment]
It should display that there is an update available now

**Comment by jza34** [comment]
I did upgrade and message gone! But new error message :

> "SQLSTATE[HY000]: General error: 1 no such column: button_1_url (SQL: CREATE TEMPORARY TABLE __temp__dizoo_slider_slides AS SELECT id, title, sort_order, subtitle, description, button_1_active, button_1_text, button_1_color, button_2_active, button_2_text, button_1_url FROM dizoo_slider_slides)" on line 664 of /var/www/pousse-graine/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by Dahfrenk** [comment]
Thanks for testing it, considering that the fallback works I added it to all the drop query's that it runs when uninstalling in PR https://github.com/dizoocs/slider/pull/25
After you have the newest build 1.1.4 it should not throw any errors anymore (hopefully)

**Comment by jza34** [comment]
Thanks! It works now, I uninstalled the plugin with no problems. For your interest I want to tell you that I use another slider, Slick Slider, because it is easier to customize the carousel options from the backend. But I must say, on the other side, that your backend management is better...Great work and thank you again for coding open source! All the best
